name: hits-downloader
channels:
  - conda-forge
dependencies:
  - sunpy
  - zarr
  - numcodecs
  - xarray
  - cftime
  - pip
  - pip:
    - streamlit
    - git+https://github.com/RobertJaro/InstrumentToInstrument.git