name: search-preprocess
channels:
  - conda-forge
dependencies:
  - sunpy
  - zarr
  - numcodecs
  - imagecodecs
  - xarray
  - cftime
  - pip
  - pip:
    - streamlit
    - git+https://github.com/amunozj/InstrumentToInstrument.git